### ISSUE TITLE
Loja? (Playgroup Temp Location / Work Room)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-three#146]
Buying an `€800k` Farm+Forest https://github.com/dwyl/phase-three/issues/144 might be overwhelming for @iteles right now. 💭 
But our _immediate_ challenge is childcare. We've wanted to create a playgroup for a while https://github.com/bmhco/shared/issues/13
Our children _already_ regularly play in the park near `@home` and _love_ it; it's the biggest grass area _close_ to `@home`. 
What if we could make it the playground for our playgroup? 

A shop has just come on the market 100m from @home: https://www.remax.pt/123331024-809
<img width="1097" alt="image" src="https://github.com/dwyl/phase-three/assets/194400/576d3463-e4de-465e-8368-5139fd5011d4">

![image](https://github.com/dwyl/phase-three/assets/194400/ba090b4e-b32c-4f7b-9d0d-8d8e1ce00531)

Individual listing photos captured for posterity:

![image](https://github.com/dwyl/phase-three/assets/194400/f48bb26f-f29f-4c38-94a1-6840682a8fec)

![image](https://github.com/dwyl/phase-three/assets/194400/12a02c7b-9b0a-48d8-b21c-1061db7a13f2)

![image](https://github.com/dwyl/phase-three/assets/194400/77484a8a-6b13-482d-8a2f-cc785088ad56)

![image](https://github.com/dwyl/phase-three/assets/194400/a1240bdc-839f-4d7e-ac9d-bded0ec55755)

![image](https://github.com/dwyl/phase-three/assets/194400/89884dcb-567d-4870-84f6-8ea11fb4311b)

![image](https://github.com/dwyl/phase-three/assets/194400/635a5815-511b-4d6c-9cda-1676c747d83f)

![image](https://github.com/dwyl/phase-three/assets/194400/1a69832e-a5c6-4b26-ad47-e3e6686aaec2)

![image](https://github.com/dwyl/phase-three/assets/194400/4e152c54-c863-462c-b8a1-c266fad9a8e1)

![image](https://github.com/dwyl/phase-three/assets/194400/8ae2695b-c76e-4cf4-8ed4-52ce8db8e9f5)

![image](https://github.com/dwyl/phase-three/assets/194400/8813e982-9360-4754-b86a-ba2746065e47)

![image](https://github.com/dwyl/phase-three/assets/194400/60a692d5-bbe2-4f6b-9bd1-a663056491f9)

# Why? 🤷‍♀️ 

Spending **`~€56k`** to get **45 m<sup>2</sup>** might seem like an absurd waste of cash ...
But bare with me a minute...

The price of these **45 m<sup>2</sup>**  is either _extortionate_ or a _bargain_ depending on your viewpoint. 💭 

## My perspective is:

When I'm [`@home`](https://github.com/dwyl/home) and want to get some focus (computer) work done, 
I head down to my desk and try to get into it; put on my headphones, close the door, focus on my screen ... 
5 minutes later I'm interrupted. Either in-person or by message. So the _deep_ work doesn't get done. 😢 

I know that when I was working from `@home` I would have _much_ preferred a dedicated space that was work-_only_.

### Longer Term ...

What if we could make `@home` _just_ for living/sleeping and have a _totally_ separate space for (computer) `work`?
The clear separation between `work` and `life` could help with mental separation and thus **work-life _balance_**. 

# What? 🤔 

_Temporarily_ a place to host the [`playgroup`](https://github.com/bmhco/shared/issues/7) until we _finish_ the `@home` garden.
This allows us to side-step the [Risk Assessment](https://github.com/bmhco/shared/issues/8) and get started _immediately_ (after minor refurb). 
Once the Garden is finished there will be _outdoor covered_ space for the playgroup.
So the "Shop" can become our co-working space ... 

## What `if` We _Didn't_ Work From `@home` ? 💭 

Working from home is _OK_ ... 
But it's simultaneously isolating (lonely) and _not_ conducive to getting _deep_ work done.
Distractions are _everywhere_ and it's _very_ easy to get knocked out of the "flow" state.
In a _dedicated_ work space it's clear to everyone that is where _`work`_ happens.
How much is _that_ worth to us? 💭 

## How Much? 💰 

**45 m<sup>2</sup> / €56k** = **`€1.24k / m2`**; over-priced? 💭 
I think it's over-priced as a piece of standalone commercial property. 🙅 
As @iteles noted when I showed the listing: "the location isn't great for a _shop_." 

But I have no intention of renting it out as a "shop"; everyone buys _everything_ online now anyway, right? 🛒 
But as a securely lockable  "extension" to `@home` that would allow people staying `@home` to have a _totally_ separate pace to `work` and thus allow us to maximise the space `@home` for _living_ and sleeping ... 💭 

At present we have our "office" in the basement ... 😬 
The basement is an "OK" as a stop-gap place to work if we don't have an alternative. ⌛ 
But it's a _horrible_ place to try and work; devoid of natural light! 🕶️ 
However the thing that makes it _horrible_ as an office makes it _perfect_ as a 2-bunk bedroom. 
You _want_ your bedroom to be dark to maximise sleep quality.

As a bedroom with 2 bunk beds in it (i.e. 4 beds) the basement room is worth `4 x €15 x 365 x 50% =~ €11k/year` 
But _crucially_ it would mean that we _wouldn't_ have our _office_ in the house. 
In the context of having a _separate_ workspace from `@home` I think it's worth _at least_ `€10k/year`
I wouldn't _pay_ this money to rent an "office" nearby the house ... But that's an incredibly "pennywise" mindset! 
Because if we can get a few _hours_ more **_high_ value _deep_ work** done it's worth _way_ more than the asking price!!

If we could have a dedicated space with ~10 sit/stand desks + monitors and panoramic window with abundant natural light
and signs reminding people not to distract others - i.e. go _outside_ to chat - we could make an _excellent_ `work` space. 👩‍💻

**Comment by nelsonic** [comment]
@iteles booked a viewing for 19:00 this evening. 🕖

**Comment by nelsonic** [comment]
The obvious downside(s) of the “shop” for a playgroup is that the front is on a road. 🛣️ 
It’s not a heavily frequented road like Av Liberdade, 🗽 
But it does have some traffic in the morning during the school run. 🚗🚙🙃
So we either need to keep the door closed to prevent escaped children wondering into the road, or put a child gate in front of the door. 💭
Either way I don’t think of this as a dealbreaker.
And as for the fumes of the passing cars. 💨
Air quality meter and corresponding filter/purifier will be run.

**Comment by nelsonic** [comment]
For me, the open questions are:
1. Are there restrictions on type of use? E.g. are we allowed to make it an office? Or “infantário”? 
2. What are the transaction fees?
2. What are the ongoing costs e.g. mandatory maintenance and council taxes. IMI? 
3. Did the unit already have utilities e.g. internet, water & electricity? (Assuming yes!) And How much were the bills? Do they have biz rates? Can we contact the previous tenant?

**Comment by nelsonic** [comment]
@iteles just FYI: while I’ve made the “Heck, Yeah!” Case above, I can also take the “bear” side. 🐻 

Locking up €60k (the axsking price) worth of cash has a huge risk and opportunity cost. What if the economy tanks and nobody wants co-living/working anymore for a few months/years? 🤷‍♂️
Are we stuck paying €200/month in Rates & Bills with zero occupancy? 💸🔥

How much is the insurance? And what if someone breaks in to steal the nice things we have in there?! 🦹‍♂️

What if there’s a damp or plumbing issue that both sets us back a few grand and means it has be closed for months?! ⏳💰🙃
Is there asbestos in the roof? 😬💀

Is there a cap on the power (electricity) such that only a handful of basic appliances can be used, i.e. no high powered computers or tools? 10kva would trip *constantly* with even a handful of decent desktop PC, a kettle and a couple of heaters in the winter. 🥶 

are we responsible for exeterior repairs e.g. roof?
What are the restrictions on painting the exterior? 
can our sign be lit? 💡

**Comment by nelsonic** [comment]
Regus coworking in Braga (reserved desk in a shared office) costs €119/month: https://www.regus.com/pt-pt/portugal/braga/coworking

![IMG_2745](https://github.com/dwyl/phase-three/assets/194400/ea07a676-2bc7-4c00-9353-ef5a2285b056)
![IMG_2746](https://github.com/dwyl/phase-three/assets/194400/42fe3869-d395-4553-a267-5541cf50df14)
![IMG_2747](https://github.com/dwyl/phase-three/assets/194400/a9551f8a-6fce-4ec0-af5f-9f5d76a5a81a)
![IMG_2748](https://github.com/dwyl/phase-three/assets/194400/701c5acf-196c-467c-8346-03e2a96ecb64)
![IMG_2749](https://github.com/dwyl/phase-three/assets/194400/8fc58794-a21d-4fc1-a798-17ab45ba1e3d)
![IMG_2750](https://github.com/dwyl/phase-three/assets/194400/c705bef6-fded-46e5-a544-f82ef4a551f2)

Hot desking costs *more* than a reserved desk but means you can work at a different office if you want, e.g a day in Porto or mix up which desk you use. 
personally this wouldn’t appeal to me. I’d much rather have a dedicated desk.

but just capturing this as a reference for what a Digital Nomad or Startup Founder wanting to work *away* from their house would have to pay. 💭

**Comment by nelsonic** [comment]
Obviously _not_ comparing a 45m2 office to Regus!
Their facilities are very good. Many people will prefer the corporate vibe. I personally would prefer a smaller office with a more personal touch and less overhead. 

Don’t worry, I’m not rehashing the “FocusHub” nonsense.
I don’t want to run a *public* Co-working space that attempts to *compete* with WeWork. 🤦‍♂️
https://news.ycombinator.com/item?id=38172437

Rather, we own/operate an ultra low-overhead space with no receptionist or other employee to “manage” it; just a basic site where members can post comments/feedback with images. 
each member has keycard and can access 24/7/365 and CCTV monitors sed access. 
Initially just for the people staying @home but if there is demand, allow select DiNos that *live* in Braga and need a workspace. Tho this is _not_ the focus. 

I think the “value proposition” to people staying @home improves *substantially* if there is a dedicated distraction-free work space. 👩‍💻
Like we can charge €20/night - easy - for a short-stay DiNo. The economics are transformed. Means we need *far* fewer people to break even.

**Comment by iteles** [comment]
I have a LOT to say on this but just in terms of pure financials, this is the extra we'd have to pay up front:

https://www.maxfinance.pt/pt-pt/simulador-de-imt-e-imposto-de-selo
<img width="579" alt="image" src="https://github.com/dwyl/phase-three/assets/4185328/e008f94e-5e14-4ca5-b631-8e07a0351ca5">

Then there should be a small amount of IMI to pay as well, maybe €200 a year or so.

**Comment by nelsonic** [comment]
Indeed. Fully expected there to be transaction costs. GOV FatCats gotta collect their Tax for doing _nothing_ so they can have their chauffeur-driven-BMWs ... 🙄

Anyway, still looking forward to seeing the space. 
Still think it's expensive for a "shop" and a bargain as a low-overhead/frills co-working office for digital nomads staying @home. 
It's *less* than a 30second walk door-to-door. Any closer and it wouldn't be a commute! 😜

**Comment by nelsonic** [comment]
went on our field trip as a team:

![IMG_2766](https://github.com/dwyl/phase-three/assets/194400/7f1c9aba-4abc-4ab5-9545-0c3ab136145b)

![IMG_2768](https://github.com/dwyl/phase-three/assets/194400/6b8e7f41-0360-4236-af20-c2fdea7125a7)
![IMG_2769](https://github.com/dwyl/phase-three/assets/194400/66f42a64-85fe-4cb2-9d52-b2b70fd73034)
![IMG_2771](https://github.com/dwyl/phase-three/assets/194400/259f1b27-df96-45dc-9999-92dbd3dd4dac)
![IMG_2776](https://github.com/dwyl/phase-three/assets/194400/c878c76c-c490-4c01-888b-7e6e292aa22e)
![IMG_2774](https://github.com/dwyl/phase-three/assets/194400/70fdce49-5188-463a-a18d-81f1096a09a3)
![IMG_2773](https://github.com/dwyl/phase-three/assets/194400/0ffb64cf-8c87-49fc-b3e7-74a38e7af9f8)

the annual IMI (council tax) is ~€300 and there are no condo costs. The electric shutter has a remote and is on the *inside* of the glass. Fine for protecting the contents, but not the windows … 🪟 
In fairness, when the AI Riots happen, Braga won’t be the _first_ place to be hit … so it’s fine, for now …

the bathroom is serviceable. But we would probably replace it with something a bit better & easier to clean.

**Comment by iteles** [comment]
The guy said that he thought the thing in the bathroom was from condensation but it's very clearly from water coming in from above so there will be roof costs to cover too 👍 

I was happy to see there was a little storage area which could be filled with shelves (tiny but tall).

**Comment by nelsonic** [comment]
Yeah, looked like a leak to me too. There wasn’t much humidity in the space. But equally not great ventilation in the bathroom. 🚽 only a problem if a lot of people would be using it … 💭

Overall I still think the space would be great for the reasons stated above. 👆 
But I’m not so sure bout the price…

The profit in real estate is made in the purchase price, not in the sale. I.e. gotta buy low. 📉
I think this is near the top end of the price range and the long overdue recession is still coming… 🥶

**Comment by nelsonic** [comment]
@iteles yesterday you attended a Workshop at [Oficina Montessori](https://www.facebook.com/oficinamontessori/) in Porto: 
Which is in a row of commercial spaces in a residential area in Foz ... 

<img width="1080" alt="image" src="https://github.com/dwyl/phase-three/assets/194400/e1d9c7c6-0467-46d6-8b88-771eeffe68e8">

![image](https://github.com/dwyl/phase-three/assets/194400/1e07061c-672f-4af5-8310-fbf10dcb5f3d)

![image](https://github.com/dwyl/phase-three/assets/194400/0aa0d95f-3dd4-4eaf-9d88-79c86fef5947)

What were your thoughts on the space? 

They started it in 2019 (pre-covid) ... ⏳ 

<img width="692" alt="image" src="https://github.com/dwyl/phase-three/assets/194400/4a2d5c9c-a1e6-41f1-923a-504da395d002">

**Comment by nelsonic** [comment]
@iteles don't know if you saw my question regarding the Oficina Montessori space ... ⬆️ ❓

**Comment by iteles** [comment]
It was a great little space! It's a loss-maker though, according to the owner, she just has it so her kids have somewhere she trusts to go (her 5yo has now moved to 'an international school' which I assume is CLIP but does a work cycle in the space from 15h30 to 17h30 and will continue to do so as she's already purchasing 6-12 materials).

It felt a little weird to have the 0-3s in the back room where there are no windows, but this is understandable because that room is only used in the mornings.

It worked well because there's space for 2 bathrooms PLUS a storage room for extra materials 👌 

<hr/>

## On this shop
Do you think we can put a ladder up to the roof to check out the state of it? I don't want to find out we need to spend another €5k on roofing and more importantly have to FIND someone who will do it for us.

### The Pros
Really, the nice things about this shop are the location and that it's a clean break.
We're both pretty saturated with the main house project here in Braga (for many reasons) and this gives us a little pilot project space that is also fresh and not weighed down by years of disappointments and personal battles.

It feels like the breath of fresh air we need.


### The Cons
Putting €60k + monthly costs into this will compromise our ability to purchase the Souselo land.

If we didn't have this little dream, I would say yes without a doubt.

**Comment by nelsonic** [comment]
We don’t have a ladder tall enough to reach the roof and definitely couldn’t scale one discretely enough. Way too many questions would be asked. 😬

by contrast, we do have an ultra-quiet drone we can fly in the park and over the roof for a few seconds to inspect it in 4k. 📷

As for the Souselo land #116 the owners have dragged their feet so much on it that I’ve pretty much lost hope they will ever sell it. ⏳

a work space is 100% complimentary to our *existing* ***profitable*** business plan. And can be used by our children in the short term. Hence me thinking it’s a no-brainer. 💭

**Comment by nelsonic** [comment]
@iteles do you want to review the drone footage? 📷 
Or should I get it off the drone and upload it here? ⬆️

**Comment by nelsonic** [comment]
Meanwhile the “for sale” sign has been removed from the shop window:

![IMG_2729](https://github.com/user-attachments/assets/50ebe86d-82b4-40b0-9f96-4f215bd7a044)

Guessing that means they’ve sold it. 😢
Still think it would have been a good investment, as outlined above, especially while I’m trying to work remotely and there’s so much noise in the house! 

Anyway, wasn’t a priority. 🙃

**Comment by carolrmc** [comment]
Maybe something else will pop up soon🤞🏼
